name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the project
      run: docker run -v "/var/run/docker.sock":"/var/run/docker.sock"
                      -v "/home/runner/work/_temp/_github_home":"/github/home"
                      -v "/home/runner/work/_temp/_github_workflow":"/github/workflow"
                      -v "/home/runner/work/CI_TEST/CI_TEST":"/github/workspace"
                      epitechcontent/epitest-docker:latest make -C /github/workspace/

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the project
      run: docker run -v "/var/run/docker.sock":"/var/run/docker.sock"
                      -v "/home/runner/work/_temp/_github_home":"/github/home"
                      -v "/home/runner/work/_temp/_github_workflow":"/github/workflow"
                      -v "/home/runner/work/CI_TEST/CI_TEST":"/github/workspace"
                      epitechcontent/epitest-docker:latest /github/workspace/run_tests.sh
